[workspace]
resolver = "2"
members = ["crates/nts3-sys", "crates/nts3", "fixtures/pass-through"]
exclude = [
    "example/smooth-echo-nih-plug",
    "example/smooth-echo-nts3-plug",
]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "none"
