[workspace]
resolver = "2"
members = [
    "crates/nts3-sys",
    "crates/nts3-macros",
    "crates/nts3",
    "fixtures/parameter-derive",
    "fixtures/pass-through",
    "fixtures/touch-probe",
    "example/smooth-echo-nts3-plug",
]
exclude = [
    "example/smooth-echo-nih-plug",
]

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = "z"
panic = "abort"
strip = "none"
