[package]
name = "smooth-echo-nts3-plug"
version = "0.1.1"
edition = "2024"
authors = ["Fraccy (ssh)"]
publish = false

[dependencies]
nts3 = { path = "../../crates/nts3" }

# 0.21.0 is pinned because its no_std build was verified for
# thumbv7em-none-eabihf. FunDSP 0.22/0.23 currently need small no_std fixes.
fundsp = { version = "=0.21.0", default-features = false }

[lib]
name = "smooth_echo"
path = "src/lib.rs"

[dev-dependencies]
nts3-sys = { path = "../../crates/nts3-sys" }
